const popularMocks = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg',
      genre_ids: [14, 28, 12, 878, 53],
      id: 460465,
      original_language: 'en',
      original_title: 'Mortal Kombat',
      overview:
        "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
      popularity: 7612.95,
      poster_path: '/6Wdl9N6dL0Hi0T1qJLWSz6gMLbd.jpg',
      release_date: '2021-04-07',
      title: 'Mortal Kombat',
      video: false,
      vote_average: 7.9,
      vote_count: 1882,
    },
    {
      adult: false,
      backdrop_path: '/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
      genre_ids: [878, 28, 18],
      id: 399566,
      original_language: 'en',
      original_title: 'Godzilla vs. Kong',
      overview:
        'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',
      popularity: 3593.413,
      poster_path: '/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg',
      release_date: '2021-03-24',
      title: 'Godzilla vs. Kong',
      video: false,
      vote_average: 8.2,
      vote_count: 5146,
    },
    {
      adult: false,
      backdrop_path: '/3FVe3OAdgz060JaxIAaUl5lo6cx.jpg',
      genre_ids: [16, 28, 12, 14, 18],
      id: 635302,
      original_language: 'ja',
      original_title: '劇場版「鬼滅の刃」無限列車編',
      overview:
        "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
      popularity: 2767.274,
      poster_path: '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
      release_date: '2020-10-16',
      title: 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train',
      video: false,
      vote_average: 8.3,
      vote_count: 745,
    },
    {
      adult: false,
      backdrop_path: '/mb3fcmQzXd8aUf7r6izZfMHSJmz.jpg',
      genre_ids: [28, 80, 53],
      id: 804435,
      original_language: 'en',
      original_title: 'Vanquish',
      overview:
        'Victoria is a young mother trying to put her dark past as a Russian drug courier behind her, but retired cop Damon forces Victoria to do his bidding by holding her daughter hostage. Now, Victoria must use guns, guts and a motorcycle to take out a series of violent gangsters—or she may never see her child again.',
      popularity: 3484.138,
      poster_path: '/AoWY1gkcNzabh229Icboa1Ff0BM.jpg',
      release_date: '2021-04-16',
      title: 'Vanquish',
      video: false,
      vote_average: 6.2,
      vote_count: 45,
    },
  ],
};

export default popularMocks;
